apiVersion: v1
kind: Service
metadata:
  name: app-aserv
  labels:
    app: ape-aserv
spec:
  type: LoadBalancer
  ports:
  - port: 5000
  selector:
    app: ape-aserv
---
apiVersion: v1
kind: Service
metadata:
  name: trace-aserv
spec:
  ports:
    - port: 8000
      targetPort: 8000
      name: zero
    - port: 8081
      targetPort: 8081
      name: one
    - port: 8082
      targetPort: 8082
      name: two
    - port: 8083
      targetPort: 8083
      name: three
  selector:
    app: ape-aserv
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: aserv
  labels:
    app: ape-aserv
  annotations:
    "sidecar.jaegertracing.io/inject": "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ape-aserv
  template:
    metadata:
      labels:
        app: ape-aserv
    spec:
      containers:
      - name: ape-aserv
        image: stephenfrench9/aserv:demo1
        ports:
        - containerPort: 5000
        - containerPort: 8000
        - containerPort: 8001
        - containerPort: 8002
        - containerPort: 8003
